Module2 task1
htmlacademy-vue/563815-pizza-1 pull request #2
Opened 2022-05-09 20:38 UTC by mikhin

2022-05-12 15:40 UTC, pisarevamarina requested changes
отличная работа! код хорошо структурирован, разбит на логичные компоненты. очень рекомендую прочитать стайл гайд по вью, он отличается от написания кода в реакте https://ru.vuejs.org/v2/style-guide/. расположение составных частей компонента следует поправить в соответствии с ним. 
нужно добавить изображения ингредиентов и  видов теста, сейчас отсутствуют.

2022-05-12 15:40 UTC, pisarevamarina commented on src/frontend/src/common/components/BasicButton.vue
> +<script>
хорошей практикой является следующий порядок в компоненте: template, script, style

2022-05-12 15:40 UTC, pisarevamarina commented on src/frontend/src/common/components/BasicButton.vue
> +<style lang="scss">
стили для элементов прописывать не нужно, верстка и стилизация уже готова, нужно лишь вешать нужный класс на элемент

2022-05-12 15:40 UTC, pisarevamarina commented on src/frontend/src/common/components/BasicCounter.vue
> +    handleCountInput(event) {
очень реактовский стиль именования функций) во вью редко употребляют приставку handle

2022-05-12 15:40 UTC, pisarevamarina commented on src/frontend/src/common/components/BasicCounter.vue
> +      type="text"
тип должен быть числовым значением

2022-05-12 15:40 UTC, pisarevamarina commented on src/frontend/src/common/components/BasicCounter.vue
> +      :disabled="count === maxIngredientCount"
по хорошему нужно использовать >=

2022-05-12 15:40 UTC, pisarevamarina commented on src/frontend/src/common/components/FormField.vue
> +      :class="{
:class="['form-field__label', {'visually-hidden': mods.labelHidden}]"

2022-05-12 15:40 UTC, pisarevamarina commented on src/frontend/src/modules/PizzaBuilder/components/IngredientsSelector.vue
> +            :itemId="ingredient.id"
хорошей практикой считается передавать пропсы в cebab-case

2022-05-14 16:48 UTC, mikhin commented on src/frontend/src/common/components/BasicCounter.vue
> +      type="text"
Тогда поедет верстка, т.к. появятся нативные браузерные контролы "вверх-вниз", чтобы удобнее было накликивать число, и они сломают инпут, т.к. он очень маленький.

2022-05-14 16:49 UTC, mikhin commented
> нужно добавить изображения ингредиентов и видов теста, сейчас отсутствуют

@pisarevamarina, не совсем понял о чем речь?

2022-05-14 16:55 UTC, mikhin commented on src/frontend/src/common/components/BasicButton.vue
> +<script>
Я вижу что можно и начинать со `script` – https://ru.vuejs.org/v2/style-guide/#%D0%9F%D0%BE%D1%80%D1%8F%D0%B4%D0%BE%D0%BA-%D1%81%D0%B5%D0%BA%D1%86%D0%B8%D0%B9-%D0%B2-%D0%BE%D0%B4%D0%BD%D0%BE%D1%84%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D1%8B%D1%85-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0%D1%85-%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D1%83%D0%B5%D1%82%D1%81%D1%8F

Мне кажется лучше начинать со `script`, т.к. этот блок описывает внешнее API компонента прежде всего (пропсы), а также внутреннюю реализацию — все это удобнее держать в начале файле, чтобы иметь возможность быстрее находить и ознакамливаться.

2022-05-14 16:56 UTC, mikhin commented on src/frontend/src/common/components/BasicButton.vue
> +<style lang="scss">
Решил сразу разделить по-нормальному, чтобы удобнее было, плюс об этом есть в код-стайле — https://ru.vuejs.org/v2/style-guide/#%D0%9B%D0%BE%D0%BA%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5-%D1%81%D1%82%D0%B8%D0%BB%D0%B8-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0-%D0%B2%D0%B0%D0%B6%D0%BD%D0%BE

2022-05-14 16:57 UTC, mikhin commented on src/frontend/src/common/components/BasicCounter.vue
> +    handleCountInput(event) {
а как обычно обозначается обработчик события?

2022-05-14 17:03 UTC, mikhin commented
> отличная работа! код хорошо структурирован, разбит на логичные компоненты.

спасибо большое!

2022-05-15 18:08 UTC, mikhin commented on src/frontend/src/modules/PizzaBuilder/components/IngredientsSelector.vue
> +            :itemId="ingredient.id"
Спасибо, включил правило, https://eslint.vuejs.org/rules/attribute-hyphenation.html

2022-05-16 19:46 UTC, pisarevamarina requested changes
все еще нет изображения ингредиентов и видов теста. осталось немного правок по стайл гайду.

2022-05-16 19:46 UTC, pisarevamarina commented on src/frontend/src/common/components/BasicCounter.vue
> +    handleCountInput(event) {
чаще всего с глагола, конкретного действия того что делает метод,(increaseCount, decreaseCount) если это просто input, можно добавить приставку on "onInput"

2022-05-16 19:46 UTC, pisarevamarina commented on src/frontend/src/common/components/BasicButton.vue
> +<script>
очень редко в проектах script ставят первым. я за несколько лет работы на вью не встретила ни одного проекта с подобным стилем. но раз ты решил писать так, то по этой же ссылке пишут, что стиль описания компонентов должен быть единым, то есть не только в этом компоненте так, а во всем проекте. суть моего комментария в том, что в сообществе вью есть принятые соглашение по описанию компонентов, и единообразные стиль упрощает чтение кода)

2022-05-16 19:46 UTC, pisarevamarina commented on src/frontend/src/modules/PizzaBuilder/PizzaBuilder.vue
> +          @change="this.handlePizzaSizeChange"
this лишний

2022-05-16 19:46 UTC, pisarevamarina commented on src/frontend/src/modules/PizzaBuilder/components/IngredientsSelector.vue
> +  data: function () {
data() {
    return {
     .....
   }
 }

https://v3.ru.vuejs.org/ru/guide/data-methods.html#своиства-data

2022-05-16 19:46 UTC, pisarevamarina commented on src/frontend/src/modules/PizzaBuilder/components/IngredientsSelector.vue
> +  props: {
https://ru.vuejs.org/v2/style-guide/#Порядок-опций-компонента-экземпляра-рекомендуется

сначала пропсы, потом data, computed, потом методы

2022-05-16 19:46 UTC, pisarevamarina commented on src/frontend/src/common/components/BasicButton.vue
> +<style lang="scss">
да, окей, я в общем ревью написала что это даже плюсом будет)

2022-05-16 20:02 UTC, mikhin commented on src/frontend/src/modules/PizzaBuilder/components/IngredientsSelector.vue
> +  data: function () {
Стилистика не регулируется, только тип — https://ru.vuejs.org/v2/style-guide/#%D0%94%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D0%BA%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D0%B0-%D0%B2%D0%B0%D0%B6%D0%BD%D0%BE

2022-05-16 20:03 UTC, mikhin commented on src/frontend/src/modules/PizzaBuilder/components/IngredientsSelector.vue
> +  props: {
Включил "vue/order-in-components".

2022-05-16 20:05 UTC, mikhin commented on src/frontend/src/common/components/BasicCounter.vue
> +    handleCountInput(event) {
Если не против, оставлю пока так, так как это best practise — использовать обозначения для обработчиков событий.

Писать без приставки — имхо делать менее читабельным. Писать приставку `on` не совсем корректно, т.к. `on` это всегда приставка свойства, и никогда метода.

2022-05-16 20:06 UTC, mikhin commented on src/frontend/src/common/components/BasicButton.vue
> +<script>
Йеп, все так, планирую везде использовать такой порядок.

Кстати, недавно я был на продакшен-проекте, там был именно такой порядок, и было прям клево =)

2022-05-16 20:07 UTC, mikhin commented on src/frontend/src/modules/PizzaBuilder/PizzaBuilder.vue
> +          @change="this.handlePizzaSizeChange"
Спасибо, исправил

2022-05-16 20:15 UTC, merged